version: '3.5'

x-ccache: &ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  CCACHE_MAXSIZE: 2G
  CCACHE_DIR: /ccache

services:
  ubuntu:
    image: ${IMAGE_REPO}/milvus-dev:${IMAGE_ARCH}-ubuntu${UBUNTU}-${DATE_VERSION}
    # Build devcontainer
    build:
      context: .
      dockerfile: build/docker/builder/cpu/ubuntu${UBUNTU}/Dockerfile
      cache_from:
        - ${IMAGE_REPO}/milvus-dev:${IMAGE_ARCH}-ubuntu${UBUNTU}-${LATEST_DATE_VERSION}
    # user: {{ CURRENT_ID }}
    shm_size: 2G
    environment:
      <<: *ccache
      PULSAR_ADDRESS: ${PULSAR_ADDRESS}
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS}
      MINIO_ADDRESS: ${MINIO_ADDRESS}
    volumes: &ubuntu-volumes
      - .:/go/src/github.com/milvus-io/milvus:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-ubuntu${UBUNTU}-ccache:/ccache:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-ubuntu${UBUNTU}-go-mod:/go/pkg/mod:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-ubuntu${UBUNTU}-vscode-extensions:/home/milvus/.vscode-server/extensions:delegated
    working_dir: "/go/src/github.com/milvus-io/milvus"
    # Command
    command: &ubuntu-command >
      /bin/bash -c "
        make check-proto-product && make verifiers && make unittest"
    networks:
      - milvus

  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379
    networks:
      - milvus

  pulsar:
    image: apachepulsar/pulsar:2.6.1
    command: bin/pulsar standalone
    networks:
      - milvus

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - milvus

networks:
  milvus:
