- name: querynode
  docker_container:
    name: querynode
    image: "{{image}}"
    command: "milvus run querynode"
    env:
      ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
      MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
      PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      METRICS_PORT: "9091"
    network_mode: "{{nodes_network}}" #使用Host网络，Host定义在Inventory的变量中。如果使用Bridge网络则需要Publish相关的端口