version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --initial-cluster default=http://127.0.0.1:2380
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"

  pulsar:
    image: apachepulsar/pulsar:2.6.1
    command: >
      /bin/sh -c "
                  echo "" >> /pulsar/conf/standalone.conf &&
                  echo "maxMessageSize=104857600" >> /pulsar/conf/standalone.conf &&
                  echo "" >> /pulsar/conf/standalone.conf &&
                  echo "nettyMaxFrameSizeBytes=104857600" >> /pulsar/conf/standalone.conf &&
                  sed -i 's/^defaultRetentionTimeInMinutes=.*/defaultRetentionTimeInMinutes=10080/' /pulsar/conf/broker.conf && \
                  bin/pulsar standalone"
    ports:
      - "6650:6650"
      - "18080:8080"

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

networks:
  default:
    name: milvus_dev
