- name: "minio"
  docker_container:
    name: minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    env:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: "minio server /minio_data"
    # volumes:
    #   - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: "{{dependencies_network}}" #使用Host网络，Host定义在Inventory的变量中。如果使用Bridge网络则需要Publish相关的端口