- name: "proxy"
  docker_container: 
    name: proxy
    image: "{{image}}"
    command: "milvus run proxy"
    env:
      ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
      MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
      PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      METRICS_PORT: "9098"
    network_mode: "{{nodes_network}}" #使用Host网络，Host定义在Inventory的变量中。如果使用Bridge网络则需要Publish相关的端口